TO DOリスト課題
smilingirl/smilingirl-todo pull request #1
Opened 2022-09-02 05:23 UTC by smilingirl

2022-10-03 04:43 UTC, kaibonjin requested changes
コメントした！

2022-10-03 04:43 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/entity/Todo.java
> +private Long id;
なんかここインデント変だからここ前に出してほしい

2022-10-03 04:43 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/repository/TodoRepository.java
> +
空欄ちょっと消しておいてー

2022-10-03 04:43 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/controller/TodoController.java
> +
ここの空欄も消しておいてー

2022-10-03 05:00 UTC, kaibonjin requested changes
よろしく！

2022-10-03 05:00 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/entity/Todo.java
>  private Long id;
ここもインデントお願いしたい！

2022-10-03 05:12 UTC, kaibonjin requested changes

2022-10-03 05:12 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/entity/Todo.java
>  private Long id;
@Idは問題なかった！
@GeneratedValueとprivate 行を右にインデントしてほしい！

2022-10-12 07:45 UTC, kaibonjin requested changes
もうちょい！

2022-10-12 07:45 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/service/TodoService.java
> +    public TodoService() {
これは不要だと思う！

2022-10-12 07:45 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/controller/TodoController.java
> +    TodoService todoService = new TodoService();
ここはコンストラクタを使わずに、Serviceと同じ感じでDIしてみて！
```
private final TodoService todoService;
    public TodoController(TodoService todoService) {
        this.todoService = todoService;
    }
```

こんな感じで！

2022-10-12 07:46 UTC, kaibonjin commented
とりあえず僕がコメントをした部分を修正したら動作確認できたからこの修正が終わればとりあえずTODOの最初は終わりやね！

2022-10-25 07:06 UTC, kaibonjin commented
ごめんゆうき遅くなった！
前のtitleがnullになるやつ、調査してみた結果原因がわかった！
コメントしてみたから見てみて！
あと上記の修正もpushしてくれたらうれしい！

2022-10-25 07:07 UTC, kaibonjin requested changes

2022-10-25 07:07 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/form/TodoForm.java
> +    }
ここのsetterの引数の名前がおかしい！
ここをちゃんとした引数の名前にしたらTODO登録できるはず！

2022-10-25 07:08 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/form/TodoForm.java
> +    }
できればここの返信欄でなぜここが間違ってたかを文章で説明してほしい！

2022-10-27 14:32 UTC, kaibonjin commented
おーいいね！
説明だけできればいい感じ！

2022-10-27 14:32 UTC, kaibonjin commented
とりあえずLGTMだしておく

2022-10-27 14:33 UTC, kaibonjin requested changes
LGTM！（Looks good to meの略)

2022-10-27 14:36 UTC, kaibonjin approved these changes

2022-10-27 14:48 UTC, smilingirl reviewed
ここが間違ってた理由としては、privateになってるtitleをgetterで見れるようにして、setterで変更かけようとしてるのに、引数をnameにしていて受け取れていなかった！でしょうか？
当たり前のこと言い過ぎかな？笑

2022-10-27 14:48 UTC, smilingirl commented on src/main/java/com/smilingirl/skillup/todo/form/TodoForm.java
> +    }
ここが間違ってた理由としては、privateになってるtitleをgetterで見れるようにして、setterで変更かけようとしてるのに、引数をnameにしていて受け取れていなかった！でしょうか？
当たり前のこと言い過ぎかな？笑

2022-10-27 14:51 UTC, kaibonjin commented
あってる！

2022-10-27 14:51 UTC, kaibonjin commented on src/main/java/com/smilingirl/skillup/todo/form/TodoForm.java
> +    }
ちなみに直接ここに書けば大丈夫よ！

2022-10-27 14:53 UTC, smilingirl commented on src/main/java/com/smilingirl/skillup/todo/form/TodoForm.java
> +    }
こうか！ありがとう！！

2022-10-27 14:58 UTC, kaibonjin commented
LGTMもらったら下のmerge pull request押して
そうすればこのブランチがmainのブランチにマージされて、とりあえず一件落着！

2022-10-27 14:59 UTC, merged